### ISSUE TITLE
Styling issues on new Header/Navigation

### ISSUE THREAD

**Issue by SimonSta95** [neuefische/hh-java-24-3-teamproject-team-2#23]
In Mobile mode when scrolling, texts from the **Genre dropdown** overlap with the navigation 
![image](https://github.com/user-attachments/assets/27dd9bf1-707c-4460-97f9-9145b6954b58)

**Comment by esgoet** [comment]
On what page? Doesn't seem to happen for me, but either way should be fixable by setting the z-index of the navigation
